# Learning R & Bioconductor {#learning-r-and-bioconductor}

## A Brief Overview

[R](http://www.r-project.org/) is a high-level programming language that was initially designed for statistical applications. While there is much to be said [about R](https://www.r-project.org/about.html) as a programming language, one of the key advantages of using R is that it is highly extensible through _packages_. The ease of development and distribution of packages for R has made it a rich environment for many fields of study and application.

One of the primary ways in which packages are distributed is through centralized repositories. The first R repository a user typically runs into is the [Comprehensive R Archive Network](https://cran.r-project.org/mirrors.html) (CRAN), which hosts over 13,000 packages to date, and is home to many of the most popular R packages. 

Similar to CRAN, [Bioconductor](https://bioconductor.org) is a repository of R packages as well. However, whereas CRAN is a general purpose repository, Bioconductor focuses on software tailored for genomic analysis. Furthermore, Bioconductor has stricter requirements for a package to be accepted into the repository. Of particular interest to us is the inclusion of [high quality documentation](#learning-more) and the use of common [data infrastructure](#data-infrastructure) to promote package interoperability.


## Prerequisites

To follow along with the analysis workflows in this book, there are necessary software prerequisites that must be fulfilled. These workflows are written in the [R](http://www.r-project.org/) programming language.


## Learning more {#learning-more}

R for Data Science 

Bioconductor workshop resources
- https://bioconductor.github.io/BiocWorkshops/r-and-bioconductor-for-everyone-an-introduction.html

Online courses
- https://online-learning.harvard.edu/course/data-analysis-life-sciences-5-introduction-bioconductor-annotation-and-analysis-genomes-and
- coursera by casper


## Getting help

Bioconductor package vignettes and reference manuals
Bioconductor BiocViews and workflows
Bioconductor forum
Stackoverflow and Google for more generic R programming advice


## Conventions used in this book

Talk about code font, code blocks, function references, objects, classes.
