# Learning R and More {#learning-r-and-more}

There exist many resources for learning R and other tools that may be needed to run particular bioinformatic analyses. Here we have laid out a general order for getting started with bioinformatics with an R centric approach, from top to bottom. 

For those who are just getting started - start with the first section, [_Getting Started with R_](#getting-started-with-r). With just this section, you'll have all you need to run the latest and greatest from Bioconductor and develop your own analytical workflows.

Once you are comfortable with R, check out learning some [_Nice Companions for R_](#nice-companions-for-r), which includes Shell/Bash and Git, as this will greatly expand the horizon of bioinformatic tools available to you, enhancing your ability to work with raw data using shell-based tools and helping you keep track of your code over time (with the added bonus of keeping it safe!). 

For those seeking to advance their knowledge of R further, we recommend checking out the [_Going Beyond the Basics_](#going-beyond-the-basics) for resources to become an R expert and the benefits of checking out other languages. However, note that while learning more advanced concepts in R is useful, it is by no means necessary to get started. Checking out the resources in [_Getting Started with R_](#getting-started-with-r) is more than enough to get going. 

Before programming on your own hardware, read ahead for some brief notes on installing R and Bioconductor packages in the [_Prerequisites_](#prerequisites) section.


## Getting Started with R {#getting-started-with-r}

To learn more about programming with R, we highly recommend checking out [Datacamp](https://www.datacamp.com/), which includes both introductory and advanced courses within the [R track](https://www.datacamp.com/courses/tech:r). Datacamp is all online with many free courses, with videos and a code editor/console that promotes an interactive learning experience. What we like about Datacamp is that it is more focused on topics and programming paradigms that center around data science, which is especially helpful for getting started with R. 

Beyond just Datacamp, a mainstay resource for learning R is the [R for Data Science](https://r4ds.had.co.nz/) book. This book illustrates R programming through the exploration of various data science concepts - transformation, visualization, exploration, and more. 


## Nice Companions for R {#nice-companions-for-r}

While not essential for our purposes, many bioinformatic tools require knowledge beyond just R to install, run, and import their results into R for further analysis. The most important of which are basic knowledge of the Shell/Bash utilities, for working with bioinformatic pipelines and troubleshooting (R package) installation issues, and Git for code version control.

### Shell/Bash 

Datacamp and other interactive online resources such as [Codecademy](https://www.codecademy.com/catalog/subject/all) are great places to learn some of these extra skills. We highly recommend learning [Shell/Bash](https://www.datacamp.com/courses/tech:shell), as it is the starting point for most bioinformatic processing pipelines. 

### Git 

We would recommend learning [Git](https://www.datacamp.com/courses/tech:git) next, a system for code versioning control which underlies the popular [Github](https://Github.com) repository, where many of the most popular open source tools are hosted. Learning Git is essential for not only keeping track of your own code, but also for using, managing, and contributing to open source software projects. 

For a more R centric look at using Git (and Github), we highly recommend checking out [Happy Git and Github for the useR](https://happygitwithr.com/).


## Going Beyond the Basics {#going-beyond-the-basics}

Naturally, there are myriad other things to advance your skills in R, data science, and bioinformatics. Here we'll briefly touch on this before moving on.

### Becoming an R Expert {#becoming-an-r-expert}

For a deeper dive into the finer details of the R programming language, the [Advanced R](https://adv-r.hadley.nz/). While targeted at more experienced R users and programmers, this book represents a comprehensive compendium of more advanced concepts, and touches on some of the paradigms used extensively by developers throughout Bioconductor, specifically [programming with S4](https://adv-r.hadley.nz/s4.html). 

Eventually, you'll reach the point where you have your own collection of functions, datasets, and reach the point where you will be writing your own packages. Luckily, there's a guide for just that, with the book [R Packages](http://r-pkgs.had.co.nz/). Packages are great even if just for personal use, and of course, with some polishing, can eventually become a package available on CRAN or Bioconductor. Furthermore, they are also a great way of putting together code associated with a manuscript, promoting reproducible, accessible computing practices, something we all strive for in our work.

Finally, we save the most intriguing resource for last - another book for those on the road to becoming an R expert is [R Inferno](https://www.burns-stat.com/pages/Tutor/R_inferno.pdf), which dives into many of the unique quirks of R. _Warning: this book goes *very* deep into the painstaking details of R._

### Other Languages

Another frequent question that comes up is "What else should I learn besides R?" Firstly, we believe that [honing your R skills](#getting-started-with-r) is first and foremost, and beyond just R, learning Shell/Bash and Git covered in the [_Nice Friends for R_](#nice-friends-for-r) section are already a great start. For those just getting started, these skills should become comfortable in practice before moving on.

However, there are indeed benefits to going beyond just R. At a basic level, learning other programming languages helps broaden one's perspective - similar to learning multiple spoken or written languages, learning about other programming languages (even if only in a cursory manner) helps one identify broader patterns that may be applicable across languages. 

At an applied level, work within and outside of R has made it ever more friendly now than ever before with multi-lingual setups and teams, enabling the use of the best tool for the job at hand. For example, [Python](https://www.python.org/) is another popular language used in both data science and a broader array of applications as well. R now supports a native Python interface via the [_reticulate_](https://github.com/rstudio/reticulate) package, enabling access to tools developed originally in Python such as the popular [TensorFlow](https://tensorflow.rstudio.com/) framework for machine learning applications. [C++](http://www.cplusplus.com/) is frequently used natively in R as well via [Rcpp](http://www.rcpp.org/) in packages to massively accelerate computations. Finally, multiple langauges are supported in code documents and reports through [R Markdown](https://rmarkdown.rstudio.com/lesson-5.html).
