---
title: "Usage Statistics for Bioconductor Packages"
author: "Stephanie Hicks"
output: 
    html_document:
        theme: cosmo 
        toc: true
        toc_float: true
        highlight: tango
        number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Goal

Create a figure of growth of R, Bioconductor share of 
that (growth over time), usage statistics, dependencies, 
citations, what makes Bioconductor high quality (review process,
vignettes required, review process for devs, slack is :fire:


```{r}
library(BiocPkgTools)
library(tidyverse)
library(lubridate)
library(cowplot)

pkg_data <- BiocPkgTools::biocPkgList()
names(pkg_data)

```

Packages with `SingleCell`, `RNASeq` and `Microarray` BiocViews

```{r}
sc_pkgs <- pkg_data %>% 
  filter(str_detect(biocViews, "SingleCell")) %>% 
  pull(Package)

bulk_pkgs <- pkg_data %>% 
  filter(str_detect(biocViews, "RNASeq")) %>% 
  pull(Package)

microarray_pkgs <- pkg_data %>% 
  filter(str_detect(biocViews, "Microarray")) %>% 
  pull(Package)
```


```{r}
pkgs <- BiocPkgTools::biocDownloadStats()
```

```{r}
p_number_pkgs <- pkgs %>% 
  filter(Month != "all", Year != 2019, 
         repo=="Software", 
         Package %in% sc_pkgs) %>%
  select(Package, Year) %>%
  distinct() %>%
  group_by(Year) %>%
  summarize(total_packages = n()) %>%
  arrange(desc(Year)) %>%
  ggplot(aes(x=Year,y=total_packages)) + 
  geom_point(size=3) + 
  xlab("Year") + ylab("Total Packages Contributed") +
  # ggtitle("Single-Cell Bioconductor Software Packages") + 
   geom_smooth(method="glm",
              method.args=list(family=gaussian(link="log")))
```

```{r}
# pdf("figs/bioc-singlecell-downloads-distinct-IPs.pdf", width=6, height=4)
p_distinct_IPs <- pkgs %>% 
  filter(Month != "all", Year != 2019, 
         repo=="Software", Package %in% sc_pkgs) %>% 
  group_by(Year) %>%
  summarize(Nb_of_distinct_IPs = sum(Nb_of_distinct_IPs), 
            Nb_of_downloads = sum(Nb_of_downloads)) %>% 
  ggplot(aes(x=Year,y=Nb_of_distinct_IPs)) + 
  geom_point(size=3) + 
  xlab("Year") + ylab("Downloads (distinct IPs)") +
  # ggtitle(" ") + 
  geom_smooth(method="glm", level = 0.99,
              method.args=list(family=gaussian(link="log")))
# dev.off()
```



```{r}
pdf("figs/bioc-singlecell.pdf", width=10, height=4)
p <- plot_grid(p_number_pkgs, p_distinct_IPs, ncol=2, labels = LETTERS[1:2])
title <- ggdraw() + draw_label("Usage and impact statistics for single-cell Bioconductor software packages", fontface='bold')
plot_grid(title, p, ncol=1, rel_heights=c(0.1, 1)) # rel_heights values control title margins
dev.off()
```



```{r delete-me-monthly-data}
pdf("figs/bioc-singlecell-downloads-distinct-IPs-monthly.pdf", width=6, height=4)
pkgs %>% filter(Month != "all", # repo=="Software", 
                Package %in% sc_pkgs) %>% 
  group_by(Month, Year) %>%
  summarize(Nb_of_distinct_IPs = sum(Nb_of_distinct_IPs), 
            Nb_of_downloads = sum(Nb_of_downloads)) %>% 
  mutate("date" = ymd(paste(Year, Month, "01", sep="-"))) %>% 
  ggplot(aes(x=date,y=Nb_of_distinct_IPs)) + 
  geom_point(size=3) + scale_y_log10() + 
  xlab("Year") + ylab("Count") +
  ggtitle("Number of Single-Cell Bioconductor Software\nPackages Downloaded (distinct IPs)") + 
  geom_smooth(method="glm",
              method.args=list(family=gaussian(link="log")))
dev.off()

```


## Trying with three assays


```{r}
p_number_pkgs <- pkgs %>% 
  filter(Month != "all", Year != 2019, 
         repo=="Software", 
         Package %in% c(sc_pkgs, bulk_pkgs, microarray_pkgs)) %>%
  mutate(Assay=fct_relevel(factor(ifelse(Package %in% sc_pkgs, "Single Cell", 
                     ifelse(Package %in% bulk_pkgs, "Bulk RNA-Seq", "Microarray"))), 
                        "Microarray")) %>% 
  select(Package, Year, Assay) %>%
  distinct() %>%
  group_by(Year, Assay) %>%
  summarize(total_packages = n()) %>%
  arrange(desc(Year)) %>%
  ggplot(aes(x=Year,y=total_packages, color=Assay)) + 
  geom_point(size=4) + scale_y_log10() + 
  xlab("Year") + ylab("Total Packages Contributed") 
```


```{r}
p_distinct_IPs <- pkgs %>% 
  filter(Month != "all", Year != 2019, 
         repo=="Software", 
         Package %in% c(sc_pkgs, bulk_pkgs, microarray_pkgs)) %>%
   mutate(Assay=fct_relevel(factor(ifelse(Package %in% sc_pkgs, "Single Cell", 
                     ifelse(Package %in% bulk_pkgs, "Bulk RNA-Seq", "Microarray"))), 
                        "Microarray")) %>% 
  group_by(Year, Assay) %>%
  summarize(Nb_of_distinct_IPs = sum(Nb_of_distinct_IPs), 
            Nb_of_downloads = sum(Nb_of_downloads)) %>% 
  ggplot(aes(x=Year,y=Nb_of_distinct_IPs, color=Assay)) + 
  geom_point(size=4) + scale_y_log10() + 
  xlab("Year") + ylab("Downloads (distinct IPs)")
```



```{r}
pdf("figs/bioc-three-assays.pdf", width=9, height=4)
p <- plot_grid(p_number_pkgs + theme(legend.position = "none"), 
               p_distinct_IPs + theme(legend.position = "none"), ncol=2, labels = LETTERS[1:2])
legend <- get_legend(p_number_pkgs + theme(legend.position = "bottom"))
p2 <- plot_grid(p,legend, rel_heights = c(2,.15), ncol=1) # c(1.25, .23))
title <- ggdraw() + draw_label("Usage and impact statistics for Bioconductor software packages", fontface='bold')
plot_grid(title, p2, ncol=1, rel_heights=c(0.1, 1)) # rel_heights values control title margins
dev.off()
```